package com.example.backend.auth.service;

import com.example.backend.auth.dto.AuthResponse;
import com.example.backend.auth.dto.LoginRequest;
import com.example.backend.auth.dto.RegisterRequest;
import com.example.backend.auth.entity.Credential;
import com.example.backend.auth.entity.RefreshToken;
import com.example.backend.auth.jwt.JwtProperties;
import com.example.backend.auth.jwt.JwtService;
import com.example.backend.auth.repository.CredentialRepository;
import com.example.backend.auth.repository.RefreshTokenRepository;
import com.example.backend.shared.exception.ApiException;
import com.example.backend.shared.exception.UnauthorizedException;
import com.example.backend.users.entity.User;
import com.example.backend.users.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.lang.reflect.Field;
import java.time.Instant;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class AuthServiceTest {

    @Mock
    private UserRepository userRepository;

    @Mock
    private CredentialRepository credentialRepository;

    @Mock
    private RefreshTokenRepository refreshTokenRepository;

    @Mock
    private PasswordEncoder passwordEncoder;

    @Mock
    private JwtService jwtService;

    @Mock
    private JwtProperties jwtProperties;

    @InjectMocks
    private AuthService authService;

    private RegisterRequest validRegisterRequest;
    private LoginRequest validLoginRequest;
    private User testUser;
    private Credential testCredential;

    @BeforeEach
    void setUp() throws Exception {
        validRegisterRequest = new RegisterRequest();
        validRegisterRequest.setUsername("newuser");
        validRegisterRequest.setEmail("newuser@example.com");
        validRegisterRequest.setPassword("password123");

        validLoginRequest = new LoginRequest();
        validLoginRequest.setUsernameOrEmail("testuser");
        validLoginRequest.setPassword("password123");

        // Note: User ID is auto-generated by JPA, we use reflection to set it for testing
        testUser = new User();
        testUser.setUsername("testuser");
        testUser.setEmail("test@example.com");
        setUserId(testUser, 1L); // Use reflection to set the ID

        testCredential = new Credential();
        testCredential.setUser(testUser);
        testCredential.setPasswordHash("$2a$10$hashedPassword");
    }

    /**
     * Helper method to set User ID using reflection since User entity doesn't have setId().
     * This is needed for testing as JPA would normally set the ID after persisting.
     */
    private void setUserId(User user, Long id) throws Exception {
        Field idField = User.class.getDeclaredField("id");
        idField.setAccessible(true);
        idField.set(user, id);
    }

    // ==================== REGISTER TESTS ====================

    @Test
    void register_WithValidData_Success() throws Exception {
        // Arrange
        User savedUser = new User();
        savedUser.setUsername("newuser");
        savedUser.setEmail("newuser@example.com");
        setUserId(savedUser, 1L);
        
        when(userRepository.existsByUsername(anyString())).thenReturn(false);
        when(userRepository.existsByEmail(anyString())).thenReturn(false);
        when(userRepository.save(any(User.class))).thenReturn(savedUser);
        when(passwordEncoder.encode(anyString())).thenReturn("encodedPassword");
        when(jwtService.generateAccessToken(anyString())).thenReturn("access-token");
        when(jwtProperties.getRefreshTokenExpirationSeconds()).thenReturn(604800L);

        // Act
        AuthResponse response = authService.register(validRegisterRequest);

        // Assert
        assertNotNull(response);
        assertNotNull(response.getAccessToken());
        assertNotNull(response.getRefreshToken());
        assertEquals("access-token", response.getAccessToken());

        // Verify the user was saved with correct data
        ArgumentCaptor<User> userCaptor = ArgumentCaptor.forClass(User.class);
        verify(userRepository).save(userCaptor.capture());
        User capturedUser = userCaptor.getValue();
        assertEquals("newuser", capturedUser.getUsername());
        assertEquals("newuser@example.com", capturedUser.getEmail());

        // Verify credential was saved with encoded password
        ArgumentCaptor<Credential> credentialCaptor = ArgumentCaptor.forClass(Credential.class);
        verify(credentialRepository).save(credentialCaptor.capture());
        Credential savedCredential = credentialCaptor.getValue();
        assertEquals("encodedPassword", savedCredential.getPasswordHash());

        // Verify refresh token was created and saved
        verify(refreshTokenRepository).save(any(RefreshToken.class));
    }

    @Test
    void register_WithDuplicateUsername_ThrowsConflict() {
        // Arrange
        when(userRepository.existsByUsername("newuser")).thenReturn(true);

        // Act & Assert
        ApiException exception = assertThrows(ApiException.class,
                () -> authService.register(validRegisterRequest));

        assertEquals(HttpStatus.CONFLICT, exception.getStatus());
        assertEquals("Username is already taken", exception.getMessage());

        // Verify no user was saved
        verify(userRepository, never()).save(any(User.class));
        verify(credentialRepository, never()).save(any(Credential.class));
    }

    @Test
    void register_WithDuplicateEmail_ThrowsConflict() {
        // Arrange
        when(userRepository.existsByUsername(anyString())).thenReturn(false);
        when(userRepository.existsByEmail("newuser@example.com")).thenReturn(true);

        // Act & Assert
        ApiException exception = assertThrows(ApiException.class,
                () -> authService.register(validRegisterRequest));

        assertEquals(HttpStatus.CONFLICT, exception.getStatus());
        assertEquals("Email is already registered", exception.getMessage());

        // Verify no user was saved
        verify(userRepository, never()).save(any(User.class));
        verify(credentialRepository, never()).save(any(Credential.class));
    }

    // ==================== LOGIN TESTS ====================

    @Test
    void login_WithValidCredentials_Success() {
        // Arrange
        when(userRepository.findByUsernameOrEmail("testuser", "testuser"))
                .thenReturn(Optional.of(testUser));
        when(credentialRepository.findByUserId(1L))
                .thenReturn(Optional.of(testCredential));
        when(passwordEncoder.matches("password123", "$2a$10$hashedPassword"))
                .thenReturn(true);
        when(jwtService.generateAccessToken("testuser"))
                .thenReturn("access-token");
        when(jwtProperties.getRefreshTokenExpirationSeconds()).thenReturn(604800L);

        // Act
        AuthResponse response = authService.login(validLoginRequest);

        // Assert
        assertNotNull(response);
        assertEquals("access-token", response.getAccessToken());
        assertNotNull(response.getRefreshToken());

        // Verify old refresh tokens were deleted (security best practice)
        verify(refreshTokenRepository).deleteByUserId(1L);
        verify(refreshTokenRepository).save(any(RefreshToken.class));
    }

    @Test
    void login_WithEmail_Success() {
        // Arrange - Test login with email instead of username
        validLoginRequest.setUsernameOrEmail("test@example.com");
        
        when(userRepository.findByUsernameOrEmail("test@example.com", "test@example.com"))
                .thenReturn(Optional.of(testUser));
        when(credentialRepository.findByUserId(testUser.getId()))
                .thenReturn(Optional.of(testCredential));
        when(passwordEncoder.matches("password123", "$2a$10$hashedPassword"))
                .thenReturn(true);
        when(jwtService.generateAccessToken("testuser"))
                .thenReturn("access-token");
        when(jwtProperties.getRefreshTokenExpirationSeconds()).thenReturn(604800L);

        // Act
        AuthResponse response = authService.login(validLoginRequest);

        // Assert
        assertNotNull(response);
        assertEquals("access-token", response.getAccessToken());
    }

    @Test
    void login_WithNonExistentUser_ThrowsUnauthorized() {
        // Arrange
        when(userRepository.findByUsernameOrEmail(anyString(), anyString()))
                .thenReturn(Optional.empty());

        // Act & Assert
        UnauthorizedException exception = assertThrows(UnauthorizedException.class,
                () -> authService.login(validLoginRequest));

        // Note: We return generic "Invalid credentials" to prevent username enumeration attacks
        assertEquals("Invalid credentials", exception.getMessage());
        verify(credentialRepository, never()).findByUserId(any());
        verify(passwordEncoder, never()).matches(anyString(), anyString());
    }

    @Test
    void login_WithWrongPassword_ThrowsUnauthorized() {
        // Arrange
        when(userRepository.findByUsernameOrEmail("testuser", "testuser"))
                .thenReturn(Optional.of(testUser));
        when(credentialRepository.findByUserId(testUser.getId()))
                .thenReturn(Optional.of(testCredential));
        when(passwordEncoder.matches("wrongpassword", "$2a$10$hashedPassword"))
                .thenReturn(false);

        validLoginRequest.setPassword("wrongpassword");

        // Act & Assert
        UnauthorizedException exception = assertThrows(UnauthorizedException.class,
                () -> authService.login(validLoginRequest));

        assertEquals("Invalid credentials", exception.getMessage());
        
        // Verify no tokens were issued
        verify(jwtService, never()).generateAccessToken(anyString());
        verify(refreshTokenRepository, never()).save(any(RefreshToken.class));
    }

    @Test
    void login_WithUserWithoutCredentials_ThrowsUnauthorized() {
        // Arrange - Edge case: user exists but has no credentials (data inconsistency)
        when(userRepository.findByUsernameOrEmail("testuser", "testuser"))
                .thenReturn(Optional.of(testUser));
        when(credentialRepository.findByUserId(testUser.getId()))
                .thenReturn(Optional.empty());

        // Act & Assert
        UnauthorizedException exception = assertThrows(UnauthorizedException.class,
                () -> authService.login(validLoginRequest));

        assertEquals("Invalid credentials", exception.getMessage());
        verify(passwordEncoder, never()).matches(anyString(), anyString());
    }

    // ==================== REFRESH TOKEN TESTS ====================

    @Test
    void refresh_WithValidToken_Success() {
        // Arrange
        String tokenValue = "valid-refresh-token";
        RefreshToken refreshToken = new RefreshToken();
        refreshToken.setToken(tokenValue);
        refreshToken.setUser(testUser);
        refreshToken.setExpiresAt(Instant.now().plusSeconds(3600)); // Valid for 1 hour

        when(refreshTokenRepository.findByToken(tokenValue))
                .thenReturn(Optional.of(refreshToken));
        when(jwtService.generateAccessToken("testuser"))
                .thenReturn("new-access-token");
        when(jwtProperties.getRefreshTokenExpirationSeconds()).thenReturn(604800L);

        // Act
        AuthResponse response = authService.refresh(tokenValue);

        // Assert
        assertNotNull(response);
        assertEquals("new-access-token", response.getAccessToken());
        assertNotNull(response.getRefreshToken());
        assertNotEquals(tokenValue, response.getRefreshToken()); // Should get a new refresh token

        // Verify old token was deleted (token rotation security practice)
        verify(refreshTokenRepository).delete(refreshToken);
        verify(refreshTokenRepository).save(any(RefreshToken.class));
    }

    @Test
    void refresh_WithExpiredToken_ThrowsUnauthorized() {
        // Arrange
        String tokenValue = "expired-refresh-token";
        RefreshToken refreshToken = new RefreshToken();
        refreshToken.setToken(tokenValue);
        refreshToken.setUser(testUser);
        refreshToken.setExpiresAt(Instant.now().minusSeconds(3600)); // Expired 1 hour ago

        when(refreshTokenRepository.findByToken(tokenValue))
                .thenReturn(Optional.of(refreshToken));

        // Act & Assert
        UnauthorizedException exception = assertThrows(UnauthorizedException.class,
                () -> authService.refresh(tokenValue));

        assertEquals("Refresh token expired", exception.getMessage());

        // Verify expired token was deleted (cleanup)
        verify(refreshTokenRepository).delete(refreshToken);
        
        // Verify no new tokens were issued
        verify(jwtService, never()).generateAccessToken(anyString());
        verify(refreshTokenRepository, never()).save(any(RefreshToken.class));
    }

    @Test
    void refresh_WithInvalidToken_ThrowsUnauthorized() {
        // Arrange
        String tokenValue = "invalid-token";
        when(refreshTokenRepository.findByToken(tokenValue))
                .thenReturn(Optional.empty());

        // Act & Assert
        UnauthorizedException exception = assertThrows(UnauthorizedException.class,
                () -> authService.refresh(tokenValue));

        assertEquals("Invalid refresh token", exception.getMessage());
        
        // Verify no tokens were issued
        verify(jwtService, never()).generateAccessToken(anyString());
        verify(refreshTokenRepository, never()).save(any(RefreshToken.class));
    }

    // ==================== TOKEN ISSUANCE TESTS ====================

    @Test
    void issueTokens_DeletesOldRefreshTokens() {
        // Arrange - This tests the private method indirectly through register
        when(userRepository.existsByUsername(anyString())).thenReturn(false);
        when(userRepository.existsByEmail(anyString())).thenReturn(false);
        when(userRepository.save(any(User.class))).thenReturn(testUser);
        when(passwordEncoder.encode(anyString())).thenReturn("encodedPassword");
        when(jwtService.generateAccessToken(anyString())).thenReturn("access-token");
        when(jwtProperties.getRefreshTokenExpirationSeconds()).thenReturn(604800L);

        // Act
        authService.register(validRegisterRequest);

        // Assert - Verify old refresh tokens are deleted before creating new one
        // This prevents token accumulation and ensures only one active refresh token per user
        // Note: testUser.getId() might be null in test, but the method is still called
        verify(refreshTokenRepository).deleteByUserId(any());
    }

    @Test
    void issueTokens_CreatesRefreshTokenWithCorrectExpiration() {
        // Arrange
        long expirationSeconds = 604800L; // 7 days
        when(userRepository.existsByUsername(anyString())).thenReturn(false);
        when(userRepository.existsByEmail(anyString())).thenReturn(false);
        when(userRepository.save(any(User.class))).thenReturn(testUser);
        when(passwordEncoder.encode(anyString())).thenReturn("encodedPassword");
        when(jwtService.generateAccessToken(anyString())).thenReturn("access-token");
        when(jwtProperties.getRefreshTokenExpirationSeconds()).thenReturn(expirationSeconds);

        // Act
        authService.register(validRegisterRequest);

        // Assert
        ArgumentCaptor<RefreshToken> tokenCaptor = ArgumentCaptor.forClass(RefreshToken.class);
        verify(refreshTokenRepository).save(tokenCaptor.capture());
        RefreshToken savedToken = tokenCaptor.getValue();

        // Verify expiration is set correctly (within 1 second tolerance for test execution time)
        Instant expectedExpiration = Instant.now().plusSeconds(expirationSeconds);
        assertTrue(savedToken.getExpiresAt().isAfter(Instant.now()));
        assertTrue(savedToken.getExpiresAt().isBefore(expectedExpiration.plusSeconds(5)));
    }
}
