package com.example.backend.auth.security;

import com.example.backend.auth.entity.Credential;
import com.example.backend.auth.repository.CredentialRepository;
import com.example.backend.users.entity.User;
import com.example.backend.users.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UsernameNotFoundException;

import java.lang.reflect.Field;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class CustomUserDetailsServiceTest {

    @Mock
    private UserRepository userRepository;

    @Mock
    private CredentialRepository credentialRepository;

    @InjectMocks
    private CustomUserDetailsService userDetailsService;

    private User testUser;
    private Credential testCredential;

    @BeforeEach
    void setUp() throws Exception {
        // Note: User ID is auto-generated by JPA, we use reflection to set it for testing
        testUser = new User();
        testUser.setUsername("testuser");
        testUser.setEmail("test@example.com");
        setUserId(testUser, 1L); // Use reflection to set the ID

        testCredential = new Credential();
        testCredential.setUser(testUser);
        testCredential.setPasswordHash("$2a$10$hashedPassword");
    }

    /**
     * Helper method to set User ID using reflection since User entity doesn't have setId().
     * This is needed for testing as JPA would normally set the ID after persisting.
     */
    private void setUserId(User user, Long id) throws Exception {
        Field idField = User.class.getDeclaredField("id");
        idField.setAccessible(true);
        idField.set(user, id);
    }

    // ==================== LOAD USER BY USERNAME TESTS ====================

    @Test
    void loadUserByUsername_WithValidUser_ReturnsUserDetails() {
        // Arrange
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(credentialRepository.findByUserId(testUser.getId()))
                .thenReturn(Optional.of(testCredential));

        // Act
        UserDetails userDetails = userDetailsService.loadUserByUsername("testuser");

        // Assert
        assertNotNull(userDetails);
        assertEquals("testuser", userDetails.getUsername());
        assertEquals("$2a$10$hashedPassword", userDetails.getPassword());
        
        // Verify it's an instance of CustomUserDetails
        assertInstanceOf(CustomUserDetails.class, userDetails);
        CustomUserDetails customUserDetails = (CustomUserDetails) userDetails;
        // Note: CustomUserDetails has getUserId() method
        assertNotNull(customUserDetails.getUserId());

        verify(userRepository).findByUsername("testuser");
        verify(credentialRepository).findByUserId(testUser.getId());
    }

    @Test
    void loadUserByUsername_WithNonExistentUser_ThrowsUsernameNotFoundException() {
        // Arrange
        when(userRepository.findByUsername("nonexistent"))
                .thenReturn(Optional.empty());

        // Act & Assert
        UsernameNotFoundException exception = assertThrows(
                UsernameNotFoundException.class,
                () -> userDetailsService.loadUserByUsername("nonexistent")
        );

        assertEquals("User not found", exception.getMessage());
        
        // Verify credentials were not queried since user doesn't exist
        verify(userRepository).findByUsername("nonexistent");
        verify(credentialRepository, never()).findByUserId(any());
    }

    @Test
    void loadUserByUsername_WithUserButNoCredentials_ThrowsUsernameNotFoundException() {
        // Arrange - Edge case: user exists but has no credentials (data inconsistency)
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(credentialRepository.findByUserId(testUser.getId()))
                .thenReturn(Optional.empty());

        // Act & Assert
        UsernameNotFoundException exception = assertThrows(
                UsernameNotFoundException.class,
                () -> userDetailsService.loadUserByUsername("testuser")
        );

        assertEquals("Credentials not found", exception.getMessage());
        
        verify(userRepository).findByUsername("testuser");
        verify(credentialRepository).findByUserId(1L);
    }

    @Test
    void loadUserByUsername_WithNullUsername_ThrowsUsernameNotFoundException() {
        // Arrange
        when(userRepository.findByUsername(null))
                .thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(UsernameNotFoundException.class,
                () -> userDetailsService.loadUserByUsername(null));
        
        verify(userRepository).findByUsername(null);
        verify(credentialRepository, never()).findByUserId(any());
    }

    @Test
    void loadUserByUsername_WithEmptyUsername_ThrowsUsernameNotFoundException() {
        // Arrange
        when(userRepository.findByUsername(""))
                .thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(UsernameNotFoundException.class,
                () -> userDetailsService.loadUserByUsername(""));
        
        verify(userRepository).findByUsername("");
        verify(credentialRepository, never()).findByUserId(any());
    }

    @Test
    void loadUserByUsername_WithWhitespaceUsername_ThrowsUsernameNotFoundException() {
        // Arrange - Edge case: username with only spaces
        when(userRepository.findByUsername("   "))
                .thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(UsernameNotFoundException.class,
                () -> userDetailsService.loadUserByUsername("   "));
        
        verify(userRepository).findByUsername("   ");
    }

    @Test
    void loadUserByUsername_IsCaseSensitive() {
        // Arrange - Test that username lookup is case-sensitive
        when(userRepository.findByUsername("TestUser"))
                .thenReturn(Optional.empty());

        // Act & Assert - Different case should not find user
        assertThrows(UsernameNotFoundException.class,
                () -> userDetailsService.loadUserByUsername("TestUser"));
        
        verify(userRepository).findByUsername("TestUser");
    }

    @Test
    void loadUserByUsername_ReturnsUserDetailsWithAuthorities() {
        // Arrange
        // Note: User ID is null in unit tests (auto-generated by JPA), so we use any()
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(credentialRepository.findByUserId(any()))
                .thenReturn(Optional.of(testCredential));

        // Act
        UserDetails userDetails = userDetailsService.loadUserByUsername("testuser");

        // Assert - Verify authorities are present (even if empty)
        assertNotNull(userDetails.getAuthorities());
        
        // Note: Current implementation likely returns empty authorities
        // If roles/authorities are added later, update this test
    }

    @Test
    void loadUserByUsername_ReturnsEnabledAccount() {
        // Arrange
        // Note: User ID is null in unit tests (auto-generated by JPA), so we use any()
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(credentialRepository.findByUserId(any()))
                .thenReturn(Optional.of(testCredential));

        // Act
        UserDetails userDetails = userDetailsService.loadUserByUsername("testuser");

        // Assert - Verify account status flags
        assertTrue(userDetails.isAccountNonExpired(), 
                "Account should not be expired");
        assertTrue(userDetails.isAccountNonLocked(), 
                "Account should not be locked");
        assertTrue(userDetails.isCredentialsNonExpired(), 
                "Credentials should not be expired");
        assertTrue(userDetails.isEnabled(), 
                "Account should be enabled");
    }

    @Test
    void loadUserByUsername_CalledMultipleTimes_QueriesDatabase() {
        // Arrange
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(credentialRepository.findByUserId(any()))
                .thenReturn(Optional.of(testCredential));

        // Act - Load user details multiple times
        UserDetails details1 = userDetailsService.loadUserByUsername("testuser");
        UserDetails details2 = userDetailsService.loadUserByUsername("testuser");

        // Assert - Both should succeed
        assertNotNull(details1);
        assertNotNull(details2);
        
        // Note: This tests that there's no caching (good for security)
        // Each authentication request should fetch fresh data
        verify(userRepository, times(2)).findByUsername("testuser");
        verify(credentialRepository, times(2)).findByUserId(any());
    }

    @Test
    void loadUserByUsername_WithSpecialCharactersInUsername_HandlesCorrectly() throws Exception {
        // Arrange - Test usernames with special characters
        User specialUser = new User();
        specialUser.setUsername("user.name+test@domain");
        specialUser.setEmail("user@example.com");
        setUserId(specialUser, 2L); // Use reflection to set the ID
        
        Credential specialCredential = new Credential();
        specialCredential.setUser(specialUser);
        specialCredential.setPasswordHash("$2a$10$hashedPassword");
        
        when(userRepository.findByUsername("user.name+test@domain"))
                .thenReturn(Optional.of(specialUser));
        when(credentialRepository.findByUserId(2L))
                .thenReturn(Optional.of(specialCredential));

        // Act
        UserDetails userDetails = userDetailsService.loadUserByUsername("user.name+test@domain");

        // Assert
        assertNotNull(userDetails);
        assertEquals("user.name+test@domain", userDetails.getUsername());
    }

    @Test
    void loadUserByUsername_IntegrationWithSpringSecurity() {
        // This test verifies the UserDetails object is compatible with Spring Security
        
        // Arrange
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(credentialRepository.findByUserId(any()))
                .thenReturn(Optional.of(testCredential));

        // Act
        UserDetails userDetails = userDetailsService.loadUserByUsername("testuser");

        // Assert - Verify all required UserDetails methods return valid values
        assertNotNull(userDetails.getUsername(), "Username must not be null");
        assertNotNull(userDetails.getPassword(), "Password must not be null");
        assertNotNull(userDetails.getAuthorities(), "Authorities must not be null");
        assertFalse(userDetails.getPassword().isEmpty(), "Password must not be empty");
        
        // Verify the object can be serialized (important for session management)
        assertDoesNotThrow(() -> userDetails.toString());
    }
}

