package com.example.backend.users.service;

import com.example.backend.shared.exception.ApiException;
import com.example.backend.shared.exception.ResourceNotFoundException;
import com.example.backend.users.dto.UpdateUserRequest;
import com.example.backend.users.dto.UserResponse;
import com.example.backend.users.entity.User;
import com.example.backend.users.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class UserServiceTest {

    @Mock
    private UserRepository userRepository;

    @InjectMocks
    private UserService userService;

    private User testUser;
    private UpdateUserRequest updateRequest;

    @BeforeEach
    void setUp() {
        // Note: User ID is auto-generated by JPA, we don't set it in tests
        testUser = new User();
        testUser.setUsername("testuser");
        testUser.setEmail("test@example.com");

        updateRequest = new UpdateUserRequest();
        updateRequest.setUsername("updateduser");
        updateRequest.setEmail("updated@example.com");
    }

    // ==================== GET CURRENT USER TESTS ====================

    @Test
    void getCurrentUser_WithValidUsername_ReturnsUser() {
        // Arrange
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));

        // Act
        UserResponse response = userService.getCurrentUser("testuser");

        // Assert
        assertNotNull(response);
        assertEquals("testuser", response.getUsername());
        assertEquals("test@example.com", response.getEmail());
        // Note: ID may be null in unit tests without database interaction
        assertNotNull(response);

        verify(userRepository).findByUsername("testuser");
    }

    @Test
    void getCurrentUser_WithInvalidUsername_ThrowsResourceNotFoundException() {
        // Arrange
        when(userRepository.findByUsername("nonexistent"))
                .thenReturn(Optional.empty());

        // Act & Assert
        ResourceNotFoundException exception = assertThrows(
                ResourceNotFoundException.class,
                () -> userService.getCurrentUser("nonexistent")
        );

        assertEquals("User not found", exception.getMessage());
        verify(userRepository).findByUsername("nonexistent");
    }

    @Test
    void getCurrentUser_WithNullUsername_ThrowsException() {
        // Arrange
        when(userRepository.findByUsername(null))
                .thenReturn(Optional.empty());

        // Act & Assert
        // Note: In production, this might be caught earlier by @Valid annotations
        assertThrows(ResourceNotFoundException.class,
                () -> userService.getCurrentUser(null));
    }

    // ==================== UPDATE CURRENT USER TESTS ====================

    @Test
    void updateCurrentUser_WithValidData_Success() {
        // Arrange
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(userRepository.existsByUsername("updateduser"))
                .thenReturn(false);
        when(userRepository.existsByEmail("updated@example.com"))
                .thenReturn(false);
        when(userRepository.save(any(User.class)))
                .thenReturn(testUser);

        // Act
        UserResponse response = userService.updateCurrentUser("testuser", updateRequest);

        // Assert
        assertNotNull(response);

        // Verify the user was updated with correct data
        ArgumentCaptor<User> userCaptor = ArgumentCaptor.forClass(User.class);
        verify(userRepository).save(userCaptor.capture());
        User savedUser = userCaptor.getValue();
        
        assertEquals("updateduser", savedUser.getUsername());
        assertEquals("updated@example.com", savedUser.getEmail());
        // Note: ID remains the same (auto-generated, not modified)
    }

    @Test
    void updateCurrentUser_WithSameUsername_Success() {
        // Arrange - User updates email but keeps same username
        updateRequest.setUsername("testuser"); // Same as current
        updateRequest.setEmail("newemail@example.com");

        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(userRepository.existsByEmail("newemail@example.com"))
                .thenReturn(false);
        when(userRepository.save(any(User.class)))
                .thenReturn(testUser);

        // Act
        UserResponse response = userService.updateCurrentUser("testuser", updateRequest);

        // Assert
        assertNotNull(response);
        
        // Should NOT check if username exists since it's the same user
        verify(userRepository, never()).existsByUsername(anyString());
        verify(userRepository).save(any(User.class));
    }

    @Test
    void updateCurrentUser_WithSameEmail_Success() {
        // Arrange - User updates username but keeps same email
        updateRequest.setUsername("newusername");
        updateRequest.setEmail("test@example.com"); // Same as current

        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(userRepository.existsByUsername("newusername"))
                .thenReturn(false);
        when(userRepository.save(any(User.class)))
                .thenReturn(testUser);

        // Act
        UserResponse response = userService.updateCurrentUser("testuser", updateRequest);

        // Assert
        assertNotNull(response);
        
        // Should NOT check if email exists since it's the same user
        verify(userRepository, never()).existsByEmail(anyString());
        verify(userRepository).save(any(User.class));
    }

    @Test
    void updateCurrentUser_WithNoChanges_Success() {
        // Arrange - User submits same data (edge case but should work)
        updateRequest.setUsername("testuser");
        updateRequest.setEmail("test@example.com");

        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(userRepository.save(any(User.class)))
                .thenReturn(testUser);

        // Act
        UserResponse response = userService.updateCurrentUser("testuser", updateRequest);

        // Assert
        assertNotNull(response);
        
        // Should NOT check existence since both username and email are unchanged
        verify(userRepository, never()).existsByUsername(anyString());
        verify(userRepository, never()).existsByEmail(anyString());
        verify(userRepository).save(any(User.class));
    }

    @Test
    void updateCurrentUser_WithDuplicateUsername_ThrowsConflict() {
        // Arrange
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(userRepository.existsByUsername("updateduser"))
                .thenReturn(true); // Username already taken by another user

        // Act & Assert
        ApiException exception = assertThrows(ApiException.class,
                () -> userService.updateCurrentUser("testuser", updateRequest));

        assertEquals(HttpStatus.CONFLICT, exception.getStatus());
        assertEquals("Username is already taken", exception.getMessage());

        // Verify user was not saved
        verify(userRepository, never()).save(any(User.class));
    }

    @Test
    void updateCurrentUser_WithDuplicateEmail_ThrowsConflict() {
        // Arrange
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(userRepository.existsByUsername("updateduser"))
                .thenReturn(false);
        when(userRepository.existsByEmail("updated@example.com"))
                .thenReturn(true); // Email already taken by another user

        // Act & Assert
        ApiException exception = assertThrows(ApiException.class,
                () -> userService.updateCurrentUser("testuser", updateRequest));

        assertEquals(HttpStatus.CONFLICT, exception.getStatus());
        assertEquals("Email is already registered", exception.getMessage());

        // Verify user was not saved
        verify(userRepository, never()).save(any(User.class));
    }

    @Test
    void updateCurrentUser_WithNonExistentUser_ThrowsResourceNotFoundException() {
        // Arrange
        when(userRepository.findByUsername("nonexistent"))
                .thenReturn(Optional.empty());

        // Act & Assert
        ResourceNotFoundException exception = assertThrows(
                ResourceNotFoundException.class,
                () -> userService.updateCurrentUser("nonexistent", updateRequest)
        );

        assertEquals("User not found", exception.getMessage());
        
        // Verify no updates were attempted
        verify(userRepository, never()).existsByUsername(anyString());
        verify(userRepository, never()).existsByEmail(anyString());
        verify(userRepository, never()).save(any(User.class));
    }

    @Test
    void updateCurrentUser_WithDifferentUsernameAndEmail_ChecksBothForDuplicates() {
        // Arrange - Both username and email are different from current
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(userRepository.existsByUsername("updateduser"))
                .thenReturn(false);
        when(userRepository.existsByEmail("updated@example.com"))
                .thenReturn(false);
        when(userRepository.save(any(User.class)))
                .thenReturn(testUser);

        // Act
        userService.updateCurrentUser("testuser", updateRequest);

        // Assert - Both checks should be performed
        verify(userRepository).existsByUsername("updateduser");
        verify(userRepository).existsByEmail("updated@example.com");
        verify(userRepository).save(any(User.class));
    }

    @Test
    void updateCurrentUser_WithBlankUsername_UpdatesSuccessfully() {
        // Arrange - Edge case: what if request has blank username?
        // Note: This should be caught by @Valid annotation in controller,
        // but testing service behavior in isolation
        updateRequest.setUsername(""); // Empty string
        
        when(userRepository.findByUsername("testuser"))
                .thenReturn(Optional.of(testUser));
        when(userRepository.existsByUsername(""))
                .thenReturn(false);
        when(userRepository.existsByEmail("updated@example.com"))
                .thenReturn(false);
        when(userRepository.save(any(User.class)))
                .thenReturn(testUser);

        // Act
        UserResponse response = userService.updateCurrentUser("testuser", updateRequest);

        // Assert
        assertNotNull(response);
        verify(userRepository).save(any(User.class));
    }
}
