spring:
  datasource:
    url: jdbc:sqlite:target/test-app.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect

app:
  jwt:
    secret: 0123456789012345678901234567890101234567890123456789012345678901
    access-token-expiration-seconds: 900
    refresh-token-expiration-seconds: 604800
